#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Memory optimized for the multi-threaded application.

CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_GPIO_NRFX_INTERRUPT=n

# Zephyr Power Management is available only when multithreading is enabled.
# It requires the idle thread to enter the low power states.
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_POWEROFF=y

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_ASSERT=n

CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_LOG_LEVEL_INF=y
CONFIG_PBUF_RX_READ_BUF_SIZE=512

CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=64

CONFIG_PRINTK=n
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n

CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

CONFIG_TIMESLICING=n
CONFIG_COMMON_LIBC_MALLOC=n
