CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_GPIO_NRFX_INTERRUPT=n

CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_POWEROFF=y

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_ASSERT=n

CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_LOG_LEVEL_INF=y
CONFIG_PBUF_RX_READ_BUF_SIZE=512

CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=100

CONFIG_PRINTK=n
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n

CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y

CONFIG_TIMESLICING=n
CONFIG_COMMON_LIBC_MALLOC=n
